"""001_initial_schema

Revision ID: 94f7ae8d80fc
Revises: 
Create Date: 2026-04-28 22:40:03.882604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '94f7ae8d80fc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('canonical_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('short_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ticker', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('cik', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('parent_company_id', sa.BigInteger(), nullable=True),
    sa.Column('public_private', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_canonical_name'), 'companies', ['canonical_name'], unique=False)
    op.create_index(op.f('ix_companies_cik'), 'companies', ['cik'], unique=False)
    op.create_index(op.f('ix_companies_ticker'), 'companies', ['ticker'], unique=False)
    op.create_table('company_aliases',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('raw_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('match_method', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'raw_name', name='uq_company_alias_source_rawname')
    )
    op.create_index(op.f('ix_company_aliases_company_id'), 'company_aliases', ['company_id'], unique=False)
    op.create_table('curated_deals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('legacy_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('buyer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('seller', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deal_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('energy_source', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('capacity_mw', sa.Integer(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('announced_date', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('duration_years', sa.Integer(), nullable=True),
    sa.Column('headline', sa.Text(), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('edgar_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('data_source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('energy_contract_mwh_million', sa.Float(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curated_deals_legacy_id'), 'curated_deals', ['legacy_id'], unique=True)
    op.create_table('data_coverage',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pillar', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('state_code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('coverage_status', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('last_ingested_at', sa.DateTime(), nullable=True),
    sa.Column('freshness_sla_hours', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('roadmap', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pillar', 'state_code', 'source', name='uq_coverage_pillar_state_source')
    )
    op.create_index(op.f('ix_data_coverage_pillar'), 'data_coverage', ['pillar'], unique=False)
    op.create_index(op.f('ix_data_coverage_state_code'), 'data_coverage', ['state_code'], unique=False)
    op.create_table('data_lineage',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('table_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('record_id', sa.BigInteger(), nullable=True),
    sa.Column('ingestion_run_id', sa.BigInteger(), nullable=True),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(), nullable=True),
    sa.Column('parser_version', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('raw_blob_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('transformation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_lineage_table_name'), 'data_lineage', ['table_name'], unique=False)
    op.create_table('energy_projects',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('flg_btm_project', sa.Boolean(), nullable=True),
    sa.Column('developer_companies', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('developer_ticker', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('eia_entity_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('eia_entity_names', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('construction_equipment_provider_companies', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('project_financing_companies', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('customer_companies', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tot_contracted_power_mw', sa.Float(), nullable=True),
    sa.Column('tot_project_cost', sa.Float(), nullable=True),
    sa.Column('project_footprint_acreage', sa.Float(), nullable=True),
    sa.Column('site_boundary_acreage', sa.Float(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('state_code', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_energy_projects_state_code'), 'energy_projects', ['state_code'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('aterio_dc_uid', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('event_description', sa.Text(), nullable=True),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_aterio_dc_uid'), 'events', ['aterio_dc_uid'], unique=False)
    op.create_index(op.f('ix_events_event_date'), 'events', ['event_date'], unique=False)
    op.create_table('generator_permits',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('source_permit_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('facility_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('permittee_raw_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('resolved_company_id', sa.BigInteger(), nullable=True),
    sa.Column('site_id', sa.BigInteger(), nullable=True),
    sa.Column('state_code', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True),
    sa.Column('county_fips', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('rated_mw_total', sa.Float(), nullable=True),
    sa.Column('num_units', sa.Integer(), nullable=True),
    sa.Column('fuel_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('permit_status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('issued_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('frs_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('naics_code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generator_permits_frs_id'), 'generator_permits', ['frs_id'], unique=False)
    op.create_index(op.f('ix_generator_permits_permittee_raw_name'), 'generator_permits', ['permittee_raw_name'], unique=False)
    op.create_index(op.f('ix_generator_permits_site_id'), 'generator_permits', ['site_id'], unique=False)
    op.create_index(op.f('ix_generator_permits_source'), 'generator_permits', ['source'], unique=False)
    op.create_index(op.f('ix_generator_permits_state_code'), 'generator_permits', ['state_code'], unique=False)
    op.create_table('ingestion_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('adapter_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('adapter_version', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('records_fetched', sa.Integer(), nullable=False),
    sa.Column('records_normalized', sa.Integer(), nullable=False),
    sa.Column('records_stored', sa.Integer(), nullable=False),
    sa.Column('records_skipped', sa.Integer(), nullable=False),
    sa.Column('trigger', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('error_log', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('config_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_runs_adapter_name'), 'ingestion_runs', ['adapter_name'], unique=False)
    op.create_table('llm_extraction_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('agent_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('prompt_version', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('input_hash', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('input_excerpt', sa.Text(), nullable=True),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tokens_prompt', sa.Integer(), nullable=True),
    sa.Column('tokens_completion', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('fallback_path', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_name', 'input_hash', name='uq_llm_run_agent_inputhash')
    )
    op.create_index('idx_llm_runs_agent_created', 'llm_extraction_runs', ['agent_name', 'created_at'], unique=False)
    op.create_table('permit_parent_review_queue',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('generator_permit_id', sa.BigInteger(), nullable=True),
    sa.Column('permittee_raw_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('candidate_parents', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('agent_run_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('reviewer_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('reviewer_decision', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_aliases',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('site_id', sa.BigInteger(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('source_record_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('match_method', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_record_id', name='uq_site_alias_source_recid')
    )
    op.create_index(op.f('ix_site_aliases_site_id'), 'site_aliases', ['site_id'], unique=False)
    op.create_table('site_company_associations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('site_id', sa.BigInteger(), nullable=True),
    sa.Column('company_id', sa.BigInteger(), nullable=True),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('source_record_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('mw_share', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'company_id', 'role', 'source', name='uq_site_company_role_source')
    )
    op.create_index(op.f('ix_site_company_associations_company_id'), 'site_company_associations', ['company_id'], unique=False)
    op.create_index(op.f('ix_site_company_associations_site_id'), 'site_company_associations', ['site_id'], unique=False)
    op.create_table('sites',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('aterio_dc_uid', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('building_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('aterio_campus_uid', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('campus_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('pct_construction', sa.Float(), nullable=True),
    sa.Column('provider_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provider_ticker', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('provider_bloomberg_ticker', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('provider_public_private', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('provider_backed_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provider_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('end_user_companies', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('construction_equipment_provider_companies', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('project_financing_companies', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('full_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('zip_code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('county_fips', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('county_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('place_fips_code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('state_code', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True),
    sa.Column('state_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country_code', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=True),
    sa.Column('country_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('site_acreage', sa.Float(), nullable=True),
    sa.Column('tot_facility_space_sqft', sa.Float(), nullable=True),
    sa.Column('tot_datacenter_space_sqft', sa.Float(), nullable=True),
    sa.Column('prov_pub_tot_power_capacity_mw', sa.Float(), nullable=True),
    sa.Column('aterio_est_mw', sa.Float(), nullable=True),
    sa.Column('aterio_est_mw_lower', sa.Float(), nullable=True),
    sa.Column('aterio_est_mw_upper', sa.Float(), nullable=True),
    sa.Column('power_capacity_mw', sa.Float(), nullable=True),
    sa.Column('tot_project_cost', sa.Float(), nullable=True),
    sa.Column('avg_market_power_cost', sa.Float(), nullable=True),
    sa.Column('yearly_pue', sa.Float(), nullable=True),
    sa.Column('tot_num_generators', sa.Integer(), nullable=True),
    sa.Column('announced_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('construction_start_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('construction_finished_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('activation_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('estimated_active_date_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cancelled_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('project_withdrawn_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('latest_satellite_picture_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('utility_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('utility_public_private', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('utility_ticker', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('bal_auth_abbr', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('bal_auth_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bal_auth_subregion_code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('bal_auth_subregion_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('datasheet_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('map_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('permit_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('capex_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('project_execution_likelihood', sa.Float(), nullable=True),
    sa.Column('is_ai_facility', sa.Boolean(), nullable=True),
    sa.Column('flg_btm_onsite_power_generation', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('record_created_at', sa.DateTime(), nullable=True),
    sa.Column('record_updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at_source', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sites_aterio_campus_uid'), 'sites', ['aterio_campus_uid'], unique=False)
    op.create_index(op.f('ix_sites_aterio_dc_uid'), 'sites', ['aterio_dc_uid'], unique=True)
    op.create_index(op.f('ix_sites_county_fips'), 'sites', ['county_fips'], unique=False)
    op.create_index(op.f('ix_sites_power_capacity_mw'), 'sites', ['power_capacity_mw'], unique=False)
    op.create_index(op.f('ix_sites_provider_name'), 'sites', ['provider_name'], unique=False)
    op.create_index(op.f('ix_sites_state_code'), 'sites', ['state_code'], unique=False)
    op.create_table('transcript_metrics',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=True),
    sa.Column('ticker', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('period', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('period_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('metric_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('metric_category', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('numeric_value', sa.Float(), nullable=True),
    sa.Column('text_value', sa.Text(), nullable=True),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('parser_version', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcript_metrics_company_id'), 'transcript_metrics', ['company_id'], unique=False)
    # NOTE: spatial_ref_sys is a PostGIS system table — do not touch it.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcript_metrics_company_id'), table_name='transcript_metrics')
    op.drop_table('transcript_metrics')
    op.drop_index(op.f('ix_sites_state_code'), table_name='sites')
    op.drop_index(op.f('ix_sites_provider_name'), table_name='sites')
    op.drop_index(op.f('ix_sites_power_capacity_mw'), table_name='sites')
    op.drop_index(op.f('ix_sites_county_fips'), table_name='sites')
    op.drop_index(op.f('ix_sites_aterio_dc_uid'), table_name='sites')
    op.drop_index(op.f('ix_sites_aterio_campus_uid'), table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_site_company_associations_site_id'), table_name='site_company_associations')
    op.drop_index(op.f('ix_site_company_associations_company_id'), table_name='site_company_associations')
    op.drop_table('site_company_associations')
    op.drop_index(op.f('ix_site_aliases_site_id'), table_name='site_aliases')
    op.drop_table('site_aliases')
    op.drop_table('permit_parent_review_queue')
    op.drop_index('idx_llm_runs_agent_created', table_name='llm_extraction_runs')
    op.drop_table('llm_extraction_runs')
    op.drop_index(op.f('ix_ingestion_runs_adapter_name'), table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    op.drop_index(op.f('ix_generator_permits_state_code'), table_name='generator_permits')
    op.drop_index(op.f('ix_generator_permits_source'), table_name='generator_permits')
    op.drop_index(op.f('ix_generator_permits_site_id'), table_name='generator_permits')
    op.drop_index(op.f('ix_generator_permits_permittee_raw_name'), table_name='generator_permits')
    op.drop_index(op.f('ix_generator_permits_frs_id'), table_name='generator_permits')
    op.drop_table('generator_permits')
    op.drop_index(op.f('ix_events_event_date'), table_name='events')
    op.drop_index(op.f('ix_events_aterio_dc_uid'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_energy_projects_state_code'), table_name='energy_projects')
    op.drop_table('energy_projects')
    op.drop_index(op.f('ix_data_lineage_table_name'), table_name='data_lineage')
    op.drop_table('data_lineage')
    op.drop_index(op.f('ix_data_coverage_state_code'), table_name='data_coverage')
    op.drop_index(op.f('ix_data_coverage_pillar'), table_name='data_coverage')
    op.drop_table('data_coverage')
    op.drop_index(op.f('ix_curated_deals_legacy_id'), table_name='curated_deals')
    op.drop_table('curated_deals')
    op.drop_index(op.f('ix_company_aliases_company_id'), table_name='company_aliases')
    op.drop_table('company_aliases')
    op.drop_index(op.f('ix_companies_ticker'), table_name='companies')
    op.drop_index(op.f('ix_companies_cik'), table_name='companies')
    op.drop_index(op.f('ix_companies_canonical_name'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
