import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { RefreshCw, Sparkles, X } from "lucide-react";
import { tokens } from "../../../styles/insightTokens";
import SessionRunner from "./SessionRunner";
import AutoGeneratedBadge from "./AutoGeneratedBadge";
import FailedLatestBanner from "./FailedLatestBanner";
import EmptyState from "./EmptyState";
import SkeletonStack from "./SkeletonStack";
import InsightSidebar from "./InsightSidebar";
import InsightDetailPane from "./InsightDetailPane";
import {
  useLatestInsightSession,
  type LatestInsight,
} from "../../../hooks/useLatestInsightSession";
import type { WebSearchUnavailableEventData } from "../../../types/sseEvents";

/**
 * AIInsightsTab — Phase 4 default-load behavior.
 *
 * On mount the tab calls `GET /api/insights/latest` (via
 * `useLatestInsightSession`) and renders the returned insights as a
 * snapshot, no SSE attached. Per UX delta §3 / §5 + PRD addendum FR-A1..A6:
 *
 *   - 200 with insights      -> render <SnapshotInsightFeed />
 *   - 200 with session=null  -> render <EmptyState /> with primary
 *                               "Generate insights" CTA (cold start)
 *   - 404                    -> same as cold start (handled in the hook)
 *   - 5xx / network          -> inline error banner with Retry
 *
 * The "Run again" button moves to the top-right of the page header,
 * styled as a secondary border-only button (or primary fill in
 * cold-start where the label flips to "Generate insights").
 *
 * No flash-of-empty during Run again: when the user clicks Run again, we
 * keep `snapshotInsights` rendered until the first
 * `InsightCompleteEvent` of the new SSE session arrives (signalled by
 * SessionRunner via `onFirstInsightComplete`). If the stream errors
 * before any insight, we restore the snapshot and show an inline error.
 */

const c = tokens.color;
const t = tokens.typography;
const s = tokens.spacing;
const r = tokens.radius;

const API_BASE = import.meta.env.VITE_API_BASE_URL || "";

const RUN_AGAIN_KEYFRAMES = `
@keyframes insightIconSpin {
  to { transform: rotate(360deg); }
}
@media (prefers-reduced-motion: reduce) {
  [data-insight-spin] { animation: none !important; }
}
`;

function envFlagV2Enabled(): boolean {
  const raw = import.meta.env.VITE_AI_INSIGHTS_V2;
  return typeof raw === "string" && raw.toLowerCase() === "true";
}

interface HealthShape {
  ai_insights_v2?: boolean;
}

function useNarrow(): boolean {
  const [narrow, setNarrow] = useState(() =>
    typeof window !== "undefined" &&
    typeof window.matchMedia === "function" &&
    window.matchMedia("(max-width: 1024px)").matches,
  );
  useEffect(() => {
    if (typeof window === "undefined" || typeof window.matchMedia !== "function") return;
    const mq = window.matchMedia("(max-width: 1024px)");
    const onChange = () => setNarrow(mq.matches);
    mq.addEventListener?.("change", onChange);
    return () => mq.removeEventListener?.("change", onChange);
  }, []);
  return narrow;
}

export default function AIInsightsTab() {
  const latest = useLatestInsightSession({ includeFailed: true });
  const narrow = useNarrow();

  // Mail-app layout state ----------------------------------------------------
  const [selectedInsightId, setSelectedInsightId] = useState<string | null>(null);
  // Single lookup of LatestInsight-shaped objects keyed by id. Populated as
  // the sidebar surfaces rows (today is always present via snapshotInsights;
  // saved + past-run rows get stashed here when clicked) so the detail pane
  // can resolve a selection even after the source list re-renders.
  const [insightLookup, setInsightLookup] = useState<
    Record<string, LatestInsight>
  >({});
  // In-memory optimistic flip for the saved-bell indicator. Rebuilt from
  // server truth on next mount.
  const [savedOverrides, setSavedOverrides] = useState<Record<string, boolean>>({});

  const [sessionId, setSessionId] = useState<string | null>(null);
  const [creating, setCreating] = useState(false);
  const [createError, setCreateError] = useState<string | null>(null);
  const [activeSessionId, setActiveSessionId] = useState<string | null>(null);
  const [isV2Enabled, setIsV2Enabled] = useState<boolean>(envFlagV2Enabled);
  const [webSearchBanner, setWebSearchBanner] =
    useState<WebSearchUnavailableEventData | null>(null);
  const [bannerDismissed, setBannerDismissed] = useState<boolean>(false);

  // True once the in-flight manual run has emitted its first
  // insight_complete; flips the body from snapshot -> live SessionRunner.
  const [firstCompleteSeen, setFirstCompleteSeen] = useState<boolean>(false);

  // Inline error to show when a Run-again stream fails before any insight.
  const [runAgainError, setRunAgainError] = useState<string | null>(null);

  // Snapshot of the prior latest-session insights, held across a manual
  // Run-again so we never blank the feed. Once the user clicks Run-again we
  // freeze the snapshot to whatever was most recently rendered.
  const [frozenSnapshot, setFrozenSnapshot] = useState<LatestInsight[] | null>(null);
  const latestInsightsRef = useRef<LatestInsight[]>([]);
  // When the chosen latest session has status==='failed', the snapshot below
  // should render the prior fully-complete session's insights instead of the
  // failed run's (typically empty) insight list. See
  // docs/plans/ai-insights-automation/09-arch-phase4-followups.md §3.
  const isFailedLatest = latest.data?.session?.status === "failed";
  const lastSuccessful = latest.data?.last_successful ?? null;
  // Live read of insights from the latest /latest fetch, used until a Run-again
  // freezes the value above. Always reflects the freshest server data.
  const liveSnapshot = useMemo<LatestInsight[]>(
    () =>
      isFailedLatest && lastSuccessful
        ? lastSuccessful.insights
        : (latest.data?.insights ?? []),
    [latest.data, isFailedLatest, lastSuccessful],
  );
  // Mirror liveSnapshot into a ref so startSession() can freeze the current
  // view at click-time without re-rendering.
  useEffect(() => {
    latestInsightsRef.current = liveSnapshot;
  }, [liveSnapshot]);
  const snapshotInsights: LatestInsight[] = frozenSnapshot ?? liveSnapshot;

  // Track whether the user has triggered a manual Run-again at least once
  // in this tab session. Drives the snapshot-vs-live render decision.
  const [manualRunRequested, setManualRunRequested] = useState<boolean>(false);

  // Feature-flag probe (unchanged from prior implementation).
  useEffect(() => {
    let cancelled = false;
    (async () => {
      const candidates = [
        `${API_BASE}/api/health`,
        `${API_BASE}/api/insights/health`,
      ];
      for (const url of candidates) {
        try {
          const res = await fetch(url, { method: "GET" });
          if (!res.ok) continue;
          const body = (await res.json()) as HealthShape;
          if (cancelled) return;
          if (typeof body.ai_insights_v2 === "boolean") {
            setIsV2Enabled(body.ai_insights_v2 || envFlagV2Enabled());
            return;
          }
        } catch {
          // try next
        }
      }
    })();
    return () => {
      cancelled = true;
    };
  }, []);

  const onWebSearchUnavailable = useCallback(
    (data: WebSearchUnavailableEventData) => {
      setWebSearchBanner(data);
    },
    [],
  );

  const startSession = useCallback(
    async (prompt?: string) => {
      setCreating(true);
      setCreateError(null);
      setRunAgainError(null);
      setFirstCompleteSeen(false);
      // Freeze the snapshot at whatever the user is currently looking at so
      // the feed cannot blank during the SSE round trip.
      setFrozenSnapshot(latestInsightsRef.current);
      try {
        const res = await fetch(`${API_BASE}/api/insights/sessions`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ focus: prompt, max_insights: 5 }),
        });
        if (!res.ok) {
          throw new Error(`POST /api/insights/sessions failed: ${res.status}`);
        }
        const body = (await res.json()) as { session_id?: string; id?: string };
        const id = body.session_id || body.id;
        if (!id) throw new Error("session_id missing from response");
        setSessionId(id);
        setActiveSessionId(id);
        setManualRunRequested(true);
      } catch (e) {
        setCreateError(e instanceof Error ? e.message : String(e));
      } finally {
        setCreating(false);
      }
    },
    [],
  );

  const onFirstInsightComplete = useCallback(() => {
    setFirstCompleteSeen(true);
    // Agentic path: insights live in Postgres + the /api/insights/latest
    // snapshot endpoint, not in the SSE stream. Refetch so the snapshot
    // picks up the new session, then drop the manual-run state so the
    // "Generating insights…" banner clears and the snapshot renders the
    // fresh insights.
    latest.refetch();
    setManualRunRequested(false);
    setSessionId(null);
    setActiveSessionId(null);
    setFrozenSnapshot(null);
  }, [latest]);

  const onStreamError = useCallback(
    (msg: string) => {
      // Restore snapshot if we never saw the first insight.
      if (!firstCompleteSeen) {
        setRunAgainError(msg);
        // Drop the manual session so the snapshot renders again. The snapshot
        // is still held in `frozenSnapshot`; clearing it lets `liveSnapshot`
        // (which reflects the freshest /latest data) take back over.
        setManualRunRequested(false);
        setSessionId(null);
        setActiveSessionId(null);
        setFrozenSnapshot(null);
      }
    },
    [firstCompleteSeen],
  );

  // Cold-start path: no past sessions ever AND no current snapshot.
  const isColdStart =
    !latest.loading &&
    latest.data !== null &&
    latest.data.session === null &&
    snapshotInsights.length === 0 &&
    !manualRunRequested;

  // Decide whether to render the live SessionRunner. We render it once a
  // manual Run-again has been requested AND either:
  //   (a) the cold-start path (no snapshot to preserve), or
  //   (b) the new session has emitted its first insight_complete.
  const showLiveRunner =
    manualRunRequested &&
    activeSessionId !== null &&
    (firstCompleteSeen || snapshotInsights.length === 0);

  const showSnapshot =
    !showLiveRunner && snapshotInsights.length > 0 && !isColdStart;

  // Mail-app layout helpers --------------------------------------------------
  // Auto-select first today insight when snapshot becomes available, or when
  // the current selection is no longer resolvable in any source.
  useEffect(() => {
    if (!showSnapshot) return;
    const todayIds = new Set(snapshotInsights.map((i) => i.id));
    const inToday = selectedInsightId && todayIds.has(selectedInsightId);
    const inLookup =
      selectedInsightId && Boolean(insightLookup[selectedInsightId]);
    if (!inToday && !inLookup) {
      setSelectedInsightId(snapshotInsights[0]?.id ?? null);
    }
  }, [showSnapshot, snapshotInsights, selectedInsightId, insightLookup]);

  const selectedInsight: LatestInsight | null = useMemo(() => {
    if (!selectedInsightId) return null;
    const inToday = snapshotInsights.find((i) => i.id === selectedInsightId);
    if (inToday) return inToday;
    return insightLookup[selectedInsightId] ?? null;
  }, [selectedInsightId, snapshotInsights, insightLookup]);

  const onSelectInsight = useCallback((ins: LatestInsight) => {
    setSelectedInsightId(ins.id);
    setInsightLookup((m) => ({ ...m, [ins.id]: ins }));
  }, []);

  const effectiveSaved = useCallback(
    (id: string, fallback: boolean): boolean =>
      savedOverrides[id] ?? fallback,
    [savedOverrides],
  );

  const handleSaveToggle = useCallback((id: string, next: boolean) => {
    setSavedOverrides((m) => ({ ...m, [id]: next }));
  }, []);

  // Failed-latest with no prior successful run to fall back on: render the
  // empty-state in the main panel (the banner is still visible above).
  const showFailedEmpty =
    isFailedLatest && !lastSuccessful && !showLiveRunner && !manualRunRequested;

  // Total used by SnapshotInsightFeed — when we're rendering the
  // last_successful insights, prefer that session's max_insights so the
  // "Insight i of N" header reflects the snapshot we're actually showing.
  const snapshotTotal =
    isFailedLatest && lastSuccessful
      ? (lastSuccessful.session.max_insights ?? lastSuccessful.insights.length)
      : (latest.data?.session?.max_insights ?? snapshotInsights.length);

  // True from click of Run-again through the agentic loop — flips to
  // false once the first insight completes (and the LiveRunner takes
  // over) OR if the request errors out. The initial-POST `creating`
  // flag only covers the few hundred ms of session creation, NOT the
  // ~30-60s of agent work; this covers the whole run so the user sees
  // continuous feedback.
  const runInProgress =
    manualRunRequested && activeSessionId !== null && !firstCompleteSeen;

  // Fallback safety net: while a manual run is in flight, poll
  // /api/insights/latest every 4s and flip out of run-in-progress as
  // soon as a NEWER session shows up. The SSE `session_complete` event
  // is the primary signal, but if the EventSource was paused (tab
  // backgrounded, network blip, browser buffering) we'd otherwise
  // never auto-update. Polling is cheap (one GET) and only runs while
  // runInProgress is true.
  useEffect(() => {
    if (!runInProgress || !activeSessionId) return;
    let cancelled = false;
    const handle = window.setInterval(() => {
      if (cancelled) return;
      latest.refetch();
    }, 4000);
    // After each refetch, when the latest session id changes (i.e.
    // backend has finalised the new run), exit run-in-progress.
    return () => {
      cancelled = true;
      window.clearInterval(handle);
    };
    // We intentionally do not depend on latest.data — the interval is
    // stable across data updates; the *separate* effect below reacts
    // to data updates.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [runInProgress, activeSessionId]);

  // When a poll picks up the new session, exit the run-in-progress UI.
  useEffect(() => {
    if (!runInProgress) return;
    if (!activeSessionId) return;
    const latestId = latest.data?.session?.id;
    if (latestId && latestId === activeSessionId) {
      // The poll resolved; the SSE handler may also be racing this,
      // but it is idempotent.
      setFirstCompleteSeen(true);
      setManualRunRequested(false);
      setSessionId(null);
      setActiveSessionId(null);
      setFrozenSnapshot(null);
    }
  }, [runInProgress, activeSessionId, latest.data]);

  // Run-again button label / styling.
  const runAgainLabel = creating || runInProgress
    ? "Generating insights…"
    : isColdStart
      ? "Generate insights"
      : "Run again";
  const runAgainAriaLabel = creating || runInProgress
    ? "Generating insights"
    : isColdStart
      ? "Generate insights"
      : "Run again";

  const buttonStyle: React.CSSProperties = isColdStart
    ? {
        background: c.brand.primary,
        color: c.text.primary,
        border: "none",
        borderRadius: r.md,
        padding: "8px 14px",
        fontSize: t.body.fontSize,
        fontWeight: 600,
        cursor: creating ? "not-allowed" : "pointer",
        display: "inline-flex",
        alignItems: "center",
        gap: 8,
        height: 32,
      }
    : {
        background: c.bg.surfaceAlt,
        color: c.text.body,
        border: `1px solid ${c.border.default}`,
        borderRadius: r.md,
        padding: "0 12px",
        fontSize: t.body.fontSize,
        fontWeight: 500,
        cursor: creating ? "not-allowed" : "pointer",
        display: "inline-flex",
        alignItems: "center",
        gap: 6,
        height: 32,
        opacity: creating ? 0.7 : 1,
      };

  const showBadge =
    !!latest.data?.session &&
    latest.data.session.created_by === "scheduler" &&
    !manualRunRequested;

  // Failed-latest banner: rendered when the chosen latest session reported
  // by the include_failed=true branch has status==='failed'. The banner
  // sits above the past-sessions+main grid and the snapshot below renders
  // last_successful.insights when present (otherwise the EmptyState).
  const showFailedBanner = isFailedLatest;

  return (
    <div
      style={{
        background: c.bg.page,
        color: c.text.primary,
        padding: `${s.s6}px ${s.s6}px ${s.s8}px`,
        maxWidth: 1280,
        margin: "0 auto",
      }}
    >
      <style>{RUN_AGAIN_KEYFRAMES}</style>
      <header
        style={{
          display: "flex",
          flexDirection: "row",
          alignItems: "flex-start",
          justifyContent: "space-between",
          gap: s.s4,
          marginBottom: s.s5,
        }}
      >
        <div style={{ display: "flex", flexDirection: "column", gap: s.s2, minWidth: 0 }}>
          <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
            <Sparkles size={18} color={c.brand.primary} aria-hidden="true" />
            <h1
              id="ai-insights-heading"
              style={{
                margin: 0,
                fontSize: t.title.fontSize + 4,
                fontWeight: 700,
                color: c.text.primary,
              }}
            >
              AI Insights
            </h1>
          </div>
          <p
            style={{
              margin: 0,
              color: c.text.caption,
              fontSize: t.body.fontSize,
            }}
          >
            Proactive synthesis over the live data — generated on demand.
          </p>
          {showBadge && latest.data?.session?.started_at ? (
            <AutoGeneratedBadge startedAt={latest.data.session.started_at} />
          ) : null}
          {createError ? (
            <span style={{ color: c.semantic.danger, fontSize: t.meta.fontSize }}>
              {createError}
            </span>
          ) : null}
          {runAgainError ? (
            <span
              role="status"
              style={{ color: c.semantic.danger, fontSize: t.meta.fontSize }}
            >
              Run failed: {runAgainError}. Your previous insights are still shown.
            </span>
          ) : null}
        </div>
        <div style={{ flex: "0 0 auto" }}>
          <button
            type="button"
            onClick={() => startSession()}
            disabled={creating || runInProgress}
            aria-label={runAgainAriaLabel}
            aria-busy={creating || runInProgress ? "true" : undefined}
            style={{
              ...buttonStyle,
              opacity: creating || runInProgress ? 0.7 : (buttonStyle.opacity ?? 1),
              cursor: creating || runInProgress ? "not-allowed" : "pointer",
            }}
          >
            {!isColdStart ? (
              <RefreshCw
                size={14}
                aria-hidden="true"
                data-insight-spin={creating || runInProgress ? "true" : undefined}
                style={
                  creating || runInProgress
                    ? { animation: "insightIconSpin 1.5s linear infinite" }
                    : undefined
                }
              />
            ) : null}
            {runAgainLabel}
          </button>
        </div>
      </header>

      {showFailedBanner && latest.data?.session ? (
        <FailedLatestBanner
          failedAt={latest.data.session.started_at}
          lastSuccessfulAt={lastSuccessful?.session.started_at ?? null}
          onRetry={() => startSession()}
        />
      ) : null}

      {webSearchBanner && !bannerDismissed ? (
        <div
          role="status"
          style={{
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
            gap: s.s3,
            background: c.bg.warningSubtle,
            border: `1px solid ${c.semantic.warning}`,
            borderRadius: r.md,
            padding: "10px 14px",
            marginBottom: s.s4,
            color: c.semantic.warning,
            fontSize: t.body.fontSize,
          }}
        >
          <span>
            Web search unavailable — citations may be missing. Reason:{" "}
            <code style={{ fontFamily: t.mono.fontFamily }}>
              {webSearchBanner.reason}
            </code>
            .
          </span>
          <button
            type="button"
            onClick={() => setBannerDismissed(true)}
            aria-label="dismiss banner"
            style={{
              display: "inline-flex",
              alignItems: "center",
              background: "transparent",
              border: "none",
              color: c.semantic.warning,
              cursor: "pointer",
              padding: 4,
            }}
          >
            <X size={14} />
          </button>
        </div>
      ) : null}

      {latest.error ? (
        <div
          role="alert"
          style={{
            background: c.bg.warningSubtle,
            border: `1px solid ${c.semantic.danger}`,
            borderRadius: r.md,
            padding: "10px 14px",
            marginBottom: s.s4,
            color: c.semantic.danger,
            fontSize: t.body.fontSize,
            display: "flex",
            justifyContent: "space-between",
            gap: s.s3,
          }}
        >
          <span>
            Could not load the most recent insight session. {latest.error}.
          </span>
          <button
            type="button"
            onClick={() => latest.refetch()}
            style={{
              background: "transparent",
              border: `1px solid ${c.semantic.danger}`,
              borderRadius: r.md,
              padding: "4px 10px",
              color: c.semantic.danger,
              fontSize: t.body.fontSize,
              fontWeight: 600,
              cursor: "pointer",
            }}
          >
            Retry
          </button>
        </div>
      ) : null}

      <div>
        {latest.loading ? (
          <SkeletonStack count={3} total={3} />
        ) : isColdStart ? (
          <EmptyState onRun={() => startSession()} />
        ) : showFailedEmpty ? (
          <EmptyState onRun={() => startSession()} />
        ) : showLiveRunner ? (
          <SessionRunner
            sessionId={activeSessionId}
            onStart={startSession}
            active={activeSessionId === sessionId}
            isV2Enabled={isV2Enabled}
            onWebSearchUnavailable={onWebSearchUnavailable}
            onFirstInsightComplete={onFirstInsightComplete}
            onStreamError={onStreamError}
          />
        ) : showSnapshot ? (
          <>
            {runInProgress ? (
              <div
                role="status"
                aria-live="polite"
                style={{
                  display: "flex",
                  alignItems: "center",
                  gap: 10,
                  padding: "10px 14px",
                  marginBottom: s.s4,
                  background: c.bg.surfaceAlt,
                  border: `1px solid ${c.border.default}`,
                  borderLeft: `3px solid ${c.brand.primary}`,
                  borderRadius: r.md,
                  color: c.text.body,
                  fontSize: t.body.fontSize,
                }}
              >
                <RefreshCw
                  size={14}
                  aria-hidden="true"
                  style={{ animation: "insightIconSpin 1.5s linear infinite" }}
                />
                <span>
                  Generating new insights — agent is querying the warehouse,
                  drilling into supply/demand-gap patterns, and grounding
                  findings via web search. This can take 30-60 seconds.
                </span>
              </div>
            ) : null}
            <div
              style={{
                display: "grid",
                gridTemplateColumns: narrow ? "1fr" : "320px 1fr",
                gap: s.s5,
                alignItems: "flex-start",
              }}
            >
              <InsightSidebar
                todayInsights={snapshotInsights}
                selectedInsightId={selectedInsightId}
                effectiveSaved={effectiveSaved}
                onSelect={onSelectInsight}
                initialSavedOpen={false}
              />
              <InsightDetailPane
                insight={selectedInsight}
                session={
                  isFailedLatest && lastSuccessful
                    ? lastSuccessful.session
                    : (latest.data?.session ?? null)
                }
                total={snapshotTotal}
                effectiveSaved={effectiveSaved}
                onSaveToggle={handleSaveToggle}
              />
            </div>
          </>
        ) : (
          // Manual run is in flight but we have no snapshot to hold (rare;
          // only reached when /latest returned an empty insights array).
          <SessionRunner
            sessionId={activeSessionId}
            onStart={startSession}
            active={activeSessionId === sessionId}
            isV2Enabled={isV2Enabled}
            onWebSearchUnavailable={onWebSearchUnavailable}
            onFirstInsightComplete={onFirstInsightComplete}
            onStreamError={onStreamError}
          />
        )}
      </div>

    </div>
  );
}
