import { tokens } from "../../../styles/insightTokens";
import { formatUtcMinute } from "./utcFormat";

/**
 * AutoGeneratedBadge — small read-only chip that reads
 *   "Auto-generated YYYY-MM-DD HH:mm UTC"
 * when the loaded session was produced by the weekly scheduler.
 *
 * Per 04a-ux-delta-phase4-implementation.md §2:
 *   - Decorative metadata (role="note"); not focusable.
 *   - Visible text uses the abbreviated form; aria-label expands to the
 *     long screen-reader-friendly form.
 *   - Reuses bg.surfaceAlt + text.faint + radius.pill from the existing
 *     token set.
 */

const c = tokens.color;
const t = tokens.typography;
const r = tokens.radius;

export interface AutoGeneratedBadgeProps {
  /** ISO8601 timestamp from session.started_at (or generated_at). */
  startedAt: string;
}

export default function AutoGeneratedBadge({ startedAt }: AutoGeneratedBadgeProps) {
  const formatted = formatUtcMinute(startedAt);
  const label = `Auto-generated ${formatted}`;
  const srLabel = `Auto-generated by weekly scheduler at ${formatted}`;
  return (
    <span
      role="note"
      aria-label={srLabel}
      style={{
        display: "inline-flex",
        alignItems: "center",
        background: c.bg.surfaceAlt,
        color: c.text.faint,
        fontSize: t.meta.fontSize,
        fontWeight: t.meta.fontWeight,
        padding: "2px 8px",
        borderRadius: r.pill,
        // not interactive, not focusable
        cursor: "default",
        userSelect: "none",
        whiteSpace: "nowrap",
      }}
    >
      {label}
    </span>
  );
}
